### ISSUE TITLE
ERRORS — BUGS? O_O

### ISSUE THREAD

**Issue by leonbakadorov** [GramThanos/falcon.js#6] opened 2023-06-18 14:22 UTC
The bottom line is that your implementation doesn't work without a .wasm file. Earlier you said that the system automatically determines which file to run. But now, when trying to use only the .JS file, an error appears that the .wasm file was not found. 

Errors:

> GET http://localhost/falcon/falcon.wasm 404 (Not Found)
> wasm streaming compile failed: TypeError: Failed to execute 'compile' on 'WebAssembly': HTTP status code is not ok
> falling back to ArrayBuffer instantiation
> GET http://localhost/falcon/falcon.wasm 404 (Not Found)
> falcon_thanos.js:747 Aborted(both async and sync fetching of the wasm failed)
> failed to asynchronously prepare wasm: RuntimeError: Aborted(both async and sync fetching of the wasm failed)
> Aborted(RuntimeError: Aborted(both async and sync fetching of the wasm failed))
> Uncaught (in promise) Error: Failed to load at falcon_thanos.js:4457:15
> Uncaught (in promise) RuntimeError: Aborted(RuntimeError: Aborted(both async and sync fetching of the wasm failed))
    at abort (falcon_thanos.js:766:21)
    at falcon_thanos.js:892:17

**Comment by GramThanos** [comment] 2023-06-18 15:00
I think this is a duplicate of #5, thus please close this one and comment on the already opened issue.

**Comment by leonbakadorov** [comment] 2023-06-18 15:34
Fine. So what is the reason why it doesn't work the way you stated earlier? (that wasm is optional and that everything should work without it)

**Comment by leonbakadorov** [comment] 2023-06-19 20:32
Or did you lie about the fact that your implementation can only work with 1 .js file?)

**Comment by GramThanos** [comment] 2023-06-19 23:04
Dear @leonbakadorov you show cased multiple times that you are interested in this project. The code is open and free, thus take it and configure it according to your needs.

If you think there is a bug, describe the bug and wait for someone to check it and maybe fix it. Alternative, if you have the skills needed, you may also fix the bug yourself and create a pull request to share it with the community.

**Comment by leonbakadorov** [comment] 2023-06-19 23:39
Just why are you misleading? It would be immediately indicated that your implementation only works with the .wasm file! But instead you say that this is not the case and that everything works without it ...

Since you say one thing and do another, can it be obvious that your job is extremely dangerous and unreliable?

Indicate in .md that this is an experimental and unstable version of the program and that it should never be used in production.

**Comment by GramThanos** [comment] 2023-06-20 00:24
Thank you for expressing your opinion.

**Closed as completed by GramThanos** 2023-06-20 00:24 UTC
